x = 0:0.2:2*pi;
y = sin(x + 1);
figure('Position', [100, 100, 800, 600]);
subplot(2, 2, 1);
plot(x, y, 'b-', 'LineWidth', 1.5);
grid on;
title('Стиль: plot() - Непрерывная интерполяция');
xlabel('Ось X'); ylabel('Ось Y');
subplot(2, 2, 2);
bar(x, y, 'FaceColor', [0.2 0.6 0.5]);
grid on;
title('Стиль: bar() - Значения в виде гистограммы');
xlabel('Ось X'); ylabel('Ось Y');
subplot(2, 2, 3);
stem(x, y, 'r', 'filled', 'LineWidth', 1.2);
grid on;
title('Стиль: stem() - Дискретные сигналы');
xlabel('Ось X'); ylabel('Ось Y');
ax = subplot(2, 2, 4, polaraxes); 
polarplot(ax, x, y, 'm-', 'LineWidth', 1.5);
title('Стиль: polarplot()');
disp('ВЫВОД ПО ЗАДАЧЕ 7:');
disp('plot - оптимален для отображения непрерывных функций.');
disp('bar - удобен для статистического сравнения величин на разных интервалах.');
disp('stem - применяется в цифровой обработке сигналов для визуализации дискретных отсчетов.');
disp('polar - демонстрирует радиальное распределение амплитуды, x интерпретируется как угол.');